package ATM;

import databaseCON.UserDAO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * The Balance class displays the current balance of the user's bank account.
 * It fetches the balance using the provided PIN and presents it to the user.
 */
public class Balance extends JFrame implements ActionListener {

    String pin;
    JLabel balanceAmountLabel;
    JButton backButton;
    UserDAO userDAO;
    private ATM atmFrame;

    /**
     * Constructs a new Balance frame.
     *
     * @param pin The PIN of the currently logged-in user, used to retrieve
     * the associated account balance.
     */
    public Balance(String pin, ATM atmFrame) {
        this.pin = pin;
        this.userDAO = new UserDAO();
        this.atmFrame = atmFrame;

        setTitle("Account Balance");
        getContentPane().setBackground(new Color(230, 240, 250));
        setLayout(null);
        setSize(600, 400);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        JLabel titleLabel = new JLabel("Your Current Balance");
        titleLabel.setFont(new Font("Segoe UI", Font.BOLD, 28));
        titleLabel.setForeground(new Color(30, 60, 90));
        titleLabel.setHorizontalAlignment(SwingConstants.CENTER);
        titleLabel.setBounds(0, 50, getWidth(), 35);
        add(titleLabel);

        JSeparator separator = new JSeparator();
        separator.setBounds(50, 110, 500, 2);
        separator.setForeground(new Color(180, 180, 180));
        add(separator);

        balanceAmountLabel = new JLabel("Fetching balance...");
        balanceAmountLabel.setForeground(new Color(0, 128, 0));
        balanceAmountLabel.setFont(new Font("Consolas", Font.BOLD, 30));
        balanceAmountLabel.setHorizontalAlignment(SwingConstants.CENTER);
        balanceAmountLabel.setBounds(0, 150, getWidth(), 40);
        add(balanceAmountLabel);

        backButton = new JButton("BACK TO ATM");
        backButton.setBounds(200, 280, 200, 45);
        backButton.setBackground(new Color(65, 125, 128));
        backButton.setForeground(Color.WHITE);
        backButton.setFont(new Font("Segoe UI", Font.BOLD, 16));
        backButton.setFocusPainted(false);
        backButton.addActionListener(this);
        add(backButton);


        double currentBalance = userDAO.getBalance(pin); //get balance using pin

        if (currentBalance == -1.0) { // Assuming -1.0 is the error indicator from getBalance
            JOptionPane.showMessageDialog(this, "Error retrieving balance. Please ensure your PIN is correct and try again.", "Balance Error", JOptionPane.ERROR_MESSAGE);
            balanceAmountLabel.setText("Balance Error");
            balanceAmountLabel.setForeground(Color.RED);
        } else {
            balanceAmountLabel.setText(String.format("%.2f CZK", currentBalance));
        }


        setVisible(true);
    }

    /**
     * Handles action events generated by the 'BACK TO ATM' button.
     * Closes the current balance display and navigates back to the main ATM menu.
     *
     * @param e The ActionEvent generated by the button click.
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == backButton) {
            this.dispose();
            atmFrame.setVisible(true);
        }
    }
}