package ATM;

import databaseCON.DatabaseConnection;
import databaseCON.UserDAO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * The Deposit class provides a graphical user interface for users to deposit money
 * into their bank account. It records the transaction in the 'bank' table.
 */
public class Deposit extends JFrame implements ActionListener {

    private String pin;
    private JTextField amountField;
    private JButton depositButton, backButton;
    private UserDAO userDAO;
    private ATM atmFrame;

    /**
     * Constructs a new Deposit frame.
     *
     * @param pin The PIN of the currently logged-in user. This PIN is used
     * to identify the user's account for the deposit transaction.
     */
    public Deposit(String pin, ATM atmFrame) {
        this.pin = pin;
        this.userDAO = new UserDAO();
        this.atmFrame = atmFrame;

        setTitle("Deposit Funds");
        getContentPane().setBackground(new Color(230, 240, 250));
        setLayout(null);
        setSize(600, 400);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Main title label
        JLabel titleLabel = new JLabel("Deposit Funds");
        titleLabel.setFont(new Font("Segoe UI", Font.BOLD, 28));
        titleLabel.setForeground(new Color(30, 60, 90));
        titleLabel.setHorizontalAlignment(SwingConstants.CENTER);
        titleLabel.setBounds(0, 50, getWidth(), 35);
        add(titleLabel);

        // Instruction label
        JLabel instructionLabel = new JLabel("ENTER AMOUNT YOU WANT TO DEPOSIT (CZK)");
        instructionLabel.setFont(new Font("Segoe UI", Font.PLAIN, 18));
        instructionLabel.setForeground(new Color(50, 50, 50));
        instructionLabel.setBounds(80, 130, 450, 25);
        add(instructionLabel);

        // Amount input field
        amountField = new JTextField();
        amountField.setFont(new Font("Consolas", Font.BOLD, 20));
        amountField.setBounds(200, 170, 200, 35);
        amountField.setBorder(BorderFactory.createLineBorder(new Color(150, 150, 150)));
        amountField.setHorizontalAlignment(JTextField.RIGHT);
        add(amountField);

        // Deposit button
        depositButton = new JButton("DEPOSIT");
        depositButton.setBackground(new Color(0, 102, 102));
        depositButton.setForeground(Color.WHITE);
        depositButton.setFont(new Font("Segoe UI", Font.BOLD, 16));
        depositButton.setFocusPainted(false);
        depositButton.setBounds(100, 270, 190, 45);
        depositButton.addActionListener(this);
        add(depositButton);

        // Back button
        backButton = new JButton("BACK TO ATM");
        backButton.setBackground(new Color(65, 125, 128));
        backButton.setForeground(Color.WHITE);
        backButton.setFont(new Font("Segoe UI", Font.BOLD, 16));
        backButton.setFocusPainted(false);
        backButton.setBounds(310, 270, 190, 45);
        backButton.addActionListener(this);
        add(backButton);

        setVisible(true);
    }

    /**
     * Handles action events generated by the buttons in the Deposit frame.
     * This method processes the deposit amount or navigates back to the ATM menu.
     *
     * @param e The ActionEvent generated by a button click.
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == backButton) {
            setVisible(false);
            new ATM(pin);
            return;
        }

        if (e.getSource() == depositButton) {
            String amountText = amountField.getText();

            if (amountText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter the Amount you want to Deposit.");
                return;
            }

            double depositAmount;
            try {
                depositAmount = Double.parseDouble(amountText);
                if (depositAmount <= 0) {
                    JOptionPane.showMessageDialog(this, "Please enter a positive amount to Deposit.");
                    return;
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Invalid amount. Please enter a numerical value.");
                return;
            }



            // Get current balance
            double currentBalance = userDAO.getBalance(pin);
            if (currentBalance == -1.0) {
                JOptionPane.showMessageDialog(this, "Error: Could not retrieve current balance. Please try again.");
                return;
            }

            double newBalance = currentBalance + depositAmount;

            boolean balanceUpdated = false;
            Connection con = null;

            try {
                con = DatabaseConnection.getConnection();
                con.setAutoCommit(false); // Start transaction

                // Update user's balance in the 'users' table
                String updateBalanceQuery = "UPDATE users SET balance = ? WHERE pin = ?";
                try (PreparedStatement pstmtUpdate = con.prepareStatement(updateBalanceQuery)) {
                    pstmtUpdate.setDouble(1, newBalance);
                    pstmtUpdate.setString(2, pin);
                    int rowsAffectedUpdate = pstmtUpdate.executeUpdate();
                    if (rowsAffectedUpdate > 0) {
                        balanceUpdated = true;
                    } else {
                        con.rollback(); // Rollback if balance update fails
                        JOptionPane.showMessageDialog(this, "Deposit failed: Could not update balance. Please try again.");
                        return;
                    }
                }

                //  Record transaction in the 'bank' table
                String insertTransactionQuery = "INSERT INTO bank (pin, date, type, amount) VALUES (?, ?, ?, ?)";
                try (PreparedStatement pstmtInsert = con.prepareStatement(insertTransactionQuery)) {
                    Date date = new Date();
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                    String formattedDate = dateFormat.format(date);

                    pstmtInsert.setString(1, pin);
                    pstmtInsert.setString(2, formattedDate);
                    pstmtInsert.setString(3, "Deposit");
                    pstmtInsert.setDouble(4, depositAmount);
                    pstmtInsert.executeUpdate();
                }

                con.commit();
                JOptionPane.showMessageDialog(this, String.format("%.2f CZK Deposited Successfully.", depositAmount));
                this.dispose();
                atmFrame.setVisible(true);

            } catch (SQLException E) {
                System.err.println("SQL Error during deposit: " + E.getMessage());
                E.printStackTrace();
                if (con != null) {
                    try {
                        con.rollback();
                    } catch (SQLException ex) {
                        System.err.println("Error during rollback: " + ex.getMessage());
                    }
                }
                JOptionPane.showMessageDialog(this, "An error occurred during deposit. Please try again.");
            } finally {
                if (con != null) {
                    try {
                        con.setAutoCommit(true);
                        con.close();
                    } catch (SQLException ex) {
                        System.err.println("Error closing connection: " + ex.getMessage());
                    }
                }
            }
        }
    }
}